# Generated by Django 3.2.15 on 2023-05-30 15:54

import apps.monitoreo.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', apps.monitoreo.models.CustomDateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
            },
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('url', models.TextField(null=True)),
                ('zoom', models.IntegerField(default=0)),
                ('target_iterations', models.IntegerField(default=0)),
                ('created_at', apps.monitoreo.models.CustomDateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'report_types',
            },
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VmwareMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dato_1', models.CharField(max_length=255)),
                ('dato_2', models.CharField(max_length=255)),
                ('dato_3', models.CharField(max_length=255)),
                ('dato_4', models.CharField(max_length=255)),
                ('dato_5', models.CharField(max_length=255)),
                ('annotation', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('ram', models.IntegerField()),
                ('processors', models.IntegerField()),
                ('sockets', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('os', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('path', models.CharField(max_length=2000, null=True)),
                ('created_at', apps.monitoreo.models.CustomDateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, to='monitoreo.report')),
                ('report_type', models.ForeignKey(db_column='report_type_id', on_delete=django.db.models.deletion.CASCADE, to='monitoreo.reporttype')),
            ],
            options={
                'db_table': 'report_screenshots',
            },
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
