# Generated by Django 3.2.15 on 2023-07-08 09:18

import apps.monitoreo.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_auto_20230530_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('path', models.CharField(max_length=2000, null=True)),
                ('created_at', apps.monitoreo.models.CustomDateTimeField(auto_now_add=True)),
                ('blinks', models.IntegerField(default=0)),
                ('report', models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, to='monitoreo.report')),
                ('report_type', models.ForeignKey(db_column='report_type_id', on_delete=django.db.models.deletion.CASCADE, to='monitoreo.reporttype')),
            ],
            options={
                'db_table': 'video_calls',
            },
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
